/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: ['Outfit', 'Inter', 'system-ui', 'sans-serif'],
        body: ['Outfit', 'Inter', 'system-ui', 'sans-serif'],
        pixel: ['"Press Start 2P"', 'monospace'],
        mono: ['"JetBrains Mono"', 'Fira Code', 'monospace'],
      },
      colors: {
        poke: {
          red: '#DC2626',
          'red-dark': '#B91C1C',
          'red-light': '#FEE2E2',
          yellow: '#D97706',
          'yellow-light': '#FEF3C7',
          blue: '#2563EB',
          'blue-light': '#DBEAFE',
          dark: '#111827',
          'dark-2': '#374151',
          'dark-3': '#1F2937',
          gray: '#E5E7EB',
          'gray-light': '#F9FAFB',
          'gray-mid': '#D1D5DB',
          'gray-dark': '#6B7280',
          white: '#FFFFFF',
          light: '#F8FAFC',
          surface: '#FFFFFF',
          'surface-2': '#F1F5F9',
          border: '#E2E8F0',
        },
        // Extended dark surface colors
        surface: {
          50:  '#F8FAFC',
          100: '#F1F5F9',
          200: '#E2E8F0',
          300: '#CBD5E1',
          400: '#94A3B8',
          500: '#64748B',
          600: '#475569',
          700: '#334155',
          800: '#1E293B',
          900: '#0F172A',
          950: '#020617',
        },
        // Pokémon type colors
        type: {
          normal:   '#9CA3AF',
          fire:     '#F97316',
          water:    '#3B82F6',
          electric: '#EAB308',
          grass:    '#22C55E',
          ice:      '#67E8F9',
          fighting: '#DC2626',
          poison:   '#A855F7',
          ground:   '#D97706',
          flying:   '#818CF8',
          psychic:  '#EC4899',
          bug:      '#84CC16',
          rock:     '#A8A29E',
          ghost:    '#6D28D9',
          dragon:   '#7C3AED',
          dark:     '#44403C',
          steel:    '#94A3B8',
          fairy:    '#F9A8D4',
        },
      },
      boxShadow: {
        'glow-red':    '0 0 20px rgba(220, 38, 38, 0.3)',
        'glow-yellow': '0 0 20px rgba(217, 119, 6, 0.3)',
        'glow-blue':   '0 0 20px rgba(37, 99, 235, 0.3)',
        'card':        '0 1px 3px rgba(0,0,0,0.08), 0 4px 16px rgba(0,0,0,0.06)',
        'card-hover':  '0 4px 12px rgba(0,0,0,0.12), 0 8px 32px rgba(0,0,0,0.08)',
        'battle':      '0 0 40px rgba(220, 38, 38, 0.2), inset 0 1px 0 rgba(255,255,255,0.1)',
      },
      backgroundImage: {
        'hero-gradient':   'linear-gradient(135deg, #0F172A 0%, #1E293B 40%, #1a1035 100%)',
        'battle-gradient': 'linear-gradient(160deg, #1a0a2e 0%, #16213e 50%, #0f3460 100%)',
        'card-gradient':   'linear-gradient(135deg, rgba(255,255,255,0.9), rgba(248,250,252,0.9))',
        'type-gradient':   'linear-gradient(135deg, var(--type-color-from), var(--type-color-to))',
        'shine':           'linear-gradient(105deg, transparent 40%, rgba(255,255,255,0.7) 50%, transparent 60%)',
      },
      animation: {
        'float':          'float 6s ease-in-out infinite',
        'float-slow':     'float 9s ease-in-out infinite',
        'spin-slow':      'spin 20s linear infinite',
        'spin-medium':    'spin 8s linear infinite',
        'slide-up':       'slideUp 0.5s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'slide-in-left':  'slideInLeft 0.4s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'slide-in-right': 'slideInRight 0.4s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'fade-in':        'fadeIn 0.4s ease-out forwards',
        'bounce-in':      'bounceIn 0.6s cubic-bezier(0.34, 1.56, 0.64, 1) forwards',
        'shimmer':        'shimmer 2s infinite',
        'battle-flash':   'battleFlash 0.3s ease-in-out',
        'hp-drain':       'hpDrain 1s ease-out forwards',
        'shake':          'shake 0.5s cubic-bezier(.36,.07,.19,.97) both',
        'pop':            'pop 0.3s cubic-bezier(0.34, 1.56, 0.64, 1) forwards',
        'typewriter':     'typewriter 0.05s steps(1) forwards',
        'pulse-slow':     'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'wiggle':         'wiggle 0.5s ease-in-out',
        'enter-left':     'enterLeft 0.6s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'enter-right':    'enterRight 0.6s cubic-bezier(0.16, 1, 0.3, 1) forwards',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%':      { transform: 'translateY(-20px)' },
        },
        slideUp: {
          from: { opacity: '0', transform: 'translateY(24px)' },
          to:   { opacity: '1', transform: 'translateY(0)' },
        },
        slideInLeft: {
          from: { opacity: '0', transform: 'translateX(-32px)' },
          to:   { opacity: '1', transform: 'translateX(0)' },
        },
        slideInRight: {
          from: { opacity: '0', transform: 'translateX(32px)' },
          to:   { opacity: '1', transform: 'translateX(0)' },
        },
        fadeIn: {
          from: { opacity: '0' },
          to:   { opacity: '1' },
        },
        bounceIn: {
          '0%':   { opacity: '0', transform: 'scale(0.3)' },
          '50%':  { opacity: '1', transform: 'scale(1.05)' },
          '70%':  { transform: 'scale(0.9)' },
          '100%': { transform: 'scale(1)' },
        },
        shimmer: {
          '0%':   { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        battleFlash: {
          '0%, 100%': { opacity: '1' },
          '50%':      { opacity: '0.2', filter: 'brightness(3)' },
        },
        hpDrain: {
          from: { width: 'var(--hp-from)' },
          to:   { width: 'var(--hp-to)' },
        },
        shake: {
          '10%, 90%': { transform: 'translate3d(-1px, 0, 0)' },
          '20%, 80%': { transform: 'translate3d(2px, 0, 0)' },
          '30%, 50%, 70%': { transform: 'translate3d(-4px, 0, 0)' },
          '40%, 60%': { transform: 'translate3d(4px, 0, 0)' },
        },
        pop: {
          '0%':   { transform: 'scale(0.8)', opacity: '0' },
          '60%':  { transform: 'scale(1.1)' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        wiggle: {
          '0%, 100%': { transform: 'rotate(-3deg)' },
          '50%': { transform: 'rotate(3deg)' },
        },
        enterLeft: {
          from: { opacity: '0', transform: 'translateX(-100px) scale(0.8)' },
          to:   { opacity: '1', transform: 'translateX(0) scale(1)' },
        },
        enterRight: {
          from: { opacity: '0', transform: 'translateX(100px) scale(0.8)' },
          to:   { opacity: '1', transform: 'translateX(0) scale(1)' },
        },
      },
      transitionTimingFunction: {
        'bounce-out': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
      },
      backdropBlur: {
        xs: '2px',
      },
    },
  },
  plugins: [],
}
